apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-explorer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-explorer-dep

  template:
    metadata:
      labels:
        app: k8s-explorer-dep

    spec:
      containers:
        - name: k8s-explorer-container
          image: k8s-explorer
          ports:
            - containerPort: 7000
          imagePullPolicy: Never