apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-explorer-rs
spec:
  replicas: 2

  selector:
    matchLabels:
      app: k8s-explorer

  template:
    metadata:
      labels:
        app: k8s-explorer
    spec:
      containers:
        - name: k8s-explorer-container
          image: k8s-explorer
          ports:
            - containerPort: 7000
          imagePullPolicy: Never

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-explorer-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: k8s-explorer-rs
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50