apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-explorer-rs
spec:
  replicas: 2

  selector:
    matchLabels:
      app: k8s-explorer

  template:
    metadata:
      labels:
        app: k8s-explorer
    spec:
      containers:
        - name: k8s-explorer-container
          image: k8s-explorer
          ports:
            - containerPort: 7000
          imagePullPolicy: Never