apiVersion: v1
kind: Pod
metadata:
  name: k8s-explorer-init-pod
spec:
  initContainers:
    - name: init-google
      image: busybox:1.28
      command: ['sh', '-c', 'sleep 2 && until nslookup google.com; do sleep 2; echo waiting for google.com; done;']
  containers:
    - name: k8s-explorer-container
      image: k8s-explorer
      ports:
        - containerPort: 7000
      imagePullPolicy: Never