
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-explorer-file-config
data:
  app.properties: |
    sleeptimeInSecondsBeforeGreet=5

---

apiVersion: v1
kind: Pod
metadata:
  name: k8s-explorer-sidecar-file-pod
spec:
  containers:
    - name: k8s-explorer-container
      image: k8s-explorer
      imagePullPolicy: Never
      ports:
        - containerPort: 7000
    - name: config-updater-sidecar-container
      image: byrnedo/alpine-curl
      command: ['sh', '-c', 'while true; do curl -X PUT -d "$(cat /etc/config/app.properties)" http://localhost:7000/config; sleep 5; done']
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: k8s-explorer-file-config